apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: slack-notifier
spec:
  notification:
    filter: build.status in [Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.TIMEOUT]
    delivery:
      webhookUrl:
        secretRef: slack-webhook-url
    template:
      type: golang
      uri: gs://<your-notifier-config-bucket>/slack.json
  secrets:
  - name: slack-webhook-url
    value: projects/<your-project-id>/secrets/slack-webhook-url/versions/latest
